feat: ability to send tracking event asynchronously
rehanvdm/serverless-website-analytics-client pull request #20
Opened 2024-04-08 13:43 UTC by m-radzikowski

If the tracking event is attached to an external link, the page is unloaded right after click.
In such case the fetch tracking request may get canceled.

This exposes "bestEffort" flag to send tracking request using beacon (Firefox) / keepalive (Chrome and others).

Closes #19

2024-04-08 19:35 UTC, rehanvdm requested changes
Looks good, I think let's just change the variable name to `isAsync` instead of `async` since `async` is also a language keyword. I was surprised to see TS/JS not complain about it, but I just want to remove the ambiguity. 

I made suggestions in the review (it can still be passed as `swa-event-async`on the HTML, its just the JS variable that needs to be different)

2024-04-08 19:35 UTC, rehanvdm commented on package/src/cdn/client-script.ts
> +          const async = (asyncAttr !== null && asyncAttr.toLowerCase() !== "false") || false;
```suggestion
          const isAsync = (asyncAttr !== null && asyncAttr.toLowerCase() !== "false") || false;
```

2024-04-08 19:35 UTC, rehanvdm commented on package/src/cdn/client-script.ts
> +          globalSwaClient.v1.analyticsTrack(trackEvent, trackDataNumber, trackCategory, async);
```suggestion
          globalSwaClient.v1.analyticsTrack(trackEvent, trackDataNumber, trackCategory, isAsync);
```

2024-04-08 19:35 UTC, rehanvdm commented on package/src/index.ts
> +   * @param async Make a request with no guarantee of delivery but a better chance of not being canceled if page is unloaded right after. Defaults to false.
```suggestion
   * @param isAsync Make a request with no guarantee of delivery but a better chance of not being canceled if page is unloaded right after. Defaults to false.
```

2024-04-08 19:35 UTC, rehanvdm commented on package/src/index.ts
> +  export function analyticsTrack(event: string, data?: number, category?: string, async: boolean = false)
```suggestion
  export function analyticsTrack(event: string, data?: number, category?: string, isAsync: boolean = false)
```

2024-04-08 19:35 UTC, rehanvdm commented on package/src/index.ts
> +    sendRequest(global.apiUrl+pathTrackEvent, JSON.stringify(trackedEvent), async);
```suggestion
    sendRequest(global.apiUrl+pathTrackEvent, JSON.stringify(trackedEvent), isAsync);
```

2024-04-09 22:18 UTC, m-radzikowski commented
Ok, all applied, thanks for making change suggestions!

2024-04-10 18:00 UTC, rehanvdm approved these changes

2024-04-10 18:01 UTC, merged